version: '3.1'
services:
  app:
    container_name: 'app_engajamento'
    image: bitnami/codeigniter:3.1.11
    restart: always
    ports:
      - 80:80
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    container_name: 'db_engajamento'
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: engajamento
      MYSQL_USER: sys_user
      MYSQL_PASSWORD: sys_password
      MYSQL_ROOT_PASSWORD: iec9Aediec9shoovoo7eiKaeliip7eCh
#      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./docker/mysql:/var/lib/mysql

