version: "3.2"
services:
  php-engajamento:
    container_name: php-engajamento
    image: php:7.4-fpm
    build:
      context: application
      dockerfile: Dockerfile
    volumes:
      - ./application/:/var/www/html
      - ./application/docker/php/config/extensions.ini:/usr/local/etc/php/conf.d/extensions.ini
    environment:
      - UPDATE_COMPOSER_DEPENDENCIES=true
      - USE_PHP_FPM=true
    ports:
      - 8081:80
    working_dir: /var/www/html/
    networks:
      - network-engajamento
  nginx-webserver-engajamento:
    container_name: nginx-webserver-engajamento
    image: nginx:1.17-alpine
    volumes:
      - ./application/:/var/www/html/
      - ./application/docker/nginx/backend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - php-engajamento
    networks:
      - network-engajamento
  database-service:
    container_name: database-engajamento
    image: postgres
    environment:
      POSTGRES_DB: 'laravel'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123456'
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - ./database/docker-data/postgres:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/
    networks:
      - network-engajamento
networks:
  network-engajamento:
    driver: bridge
